"""init

Revision ID: 73111f07c116
Revises: 
Create Date: 2026-04-09 00:49:34.307357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73111f07c116'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False, comment='计划名称，如"v2.1.3 回归测试"'),
    sa.Column('description', sa.Text(), nullable=True, comment='计划描述'),
    sa.Column('suite_ids', sa.JSON(), nullable=True, comment='选中的测试套件ID列表'),
    sa.Column('case_ids', sa.JSON(), nullable=True, comment='选中的测试用例ID列表'),
    sa.Column('case_order', sa.JSON(), nullable=True, comment='用例执行顺序配置，格式：{"global": [case_id1, case_id2, ...]}'),
    sa.Column('trigger_type', sa.String(length=32), nullable=True, comment='触发方式：manual/schedule/webhook'),
    sa.Column('schedule_cron', sa.String(length=64), nullable=True, comment='Cron表达式，如"0 2 * * *"（每天2点）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用（定时任务用）'),
    sa.Column('parallel', sa.Boolean(), nullable=True, comment='是否并行执行用例'),
    sa.Column('max_concurrent', sa.Integer(), nullable=True, comment='最大并发数'),
    sa.Column('total_runs', sa.Integer(), nullable=True, comment='总执行次数'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='上次执行时间'),
    sa.Column('last_status', sa.String(length=32), nullable=True, comment='上次执行状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='套件名称'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类:firmware/protocol/performance/power'),
    sa.Column('description', sa.Text(), nullable=True, comment='套件描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_suites_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_suites_name'), ['name'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False, comment='所属套件ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='用例名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('test_type', sa.String(length=64), nullable=True, comment='测试类型：unit/integration/system/performance'),
    sa.Column('script_content', sa.Text(), nullable=True, comment='测试脚本内容（Python代码）'),
    sa.Column('script_type', sa.String(length=32), nullable=True, comment='脚本类型：pytest/unittest/custom'),
    sa.Column('timeout', sa.Integer(), nullable=True, comment='超时时间（秒）'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级 1-4'),
    sa.Column('simulation_pass_rate', sa.Float(), nullable=True, comment='模拟通过率（0-1）'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='关联的测试计划ID'),
    sa.Column('name', sa.String(length=256), nullable=False, comment='任务名称（自动生成）'),
    sa.Column('status', sa.String(length=32), nullable=True, comment='状态：pending/running/passed/failed/cancelled'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('suite_ids', sa.JSON(), nullable=True, comment='执行的套件ID列表（快照）'),
    sa.Column('case_ids', sa.JSON(), nullable=True, comment='执行的用例ID列表（空表示全选）'),
    sa.Column('case_order', sa.JSON(), nullable=True, comment='用例执行顺序配置'),
    sa.Column('trigger_type', sa.String(length=32), nullable=True, comment='触发方式：manual/schedule'),
    sa.Column('parallel', sa.Boolean(), nullable=True, comment='是否并行执行'),
    sa.Column('max_concurrent', sa.Integer(), nullable=True, comment='最大并发数'),
    sa.Column('total_cases', sa.Integer(), nullable=True, comment='总用例数'),
    sa.Column('passed_cases', sa.Integer(), nullable=True, comment='通过数'),
    sa.Column('failed_cases', sa.Integer(), nullable=True, comment='失败数'),
    sa.Column('error_cases', sa.Integer(), nullable=True, comment='错误数'),
    sa.Column('report_json', sa.JSON(), nullable=True, comment='报告内容：{"summary": {...}, "executions": [...]}'),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True, comment='Celery任务ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['test_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_tasks')
    op.drop_table('test_cases')
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suites_name'))
        batch_op.drop_index(batch_op.f('ix_test_suites_category'))

    op.drop_table('test_suites')
    op.drop_table('test_plans')
    # ### end Alembic commands ###
